//! Media understanding engine — image description, audio transcription, video analysis.
//!
//! Auto-cascades through available providers based on configured API keys.

use openfang_types::media::{
    MediaAttachment, MediaConfig, MediaSource, MediaType, MediaUnderstanding,
};
use std::path::Path;
use std::sync::Arc;
use std::time::Duration;
use tokio::process::Command;
use tokio::sync::Semaphore;
use tracing::info;

/// Media understanding engine.
pub struct MediaEngine {
    config: MediaConfig,
    semaphore: Arc<Semaphore>,
}

impl MediaEngine {
    pub fn new(config: MediaConfig) -> Self {
        let max = config.max_concurrency.clamp(1, 8);
        Self {
            config,
            semaphore: Arc::new(Semaphore::new(max)),
        }
    }

    /// Describe an image using a vision-capable LLM.
    /// Auto-cascade: Anthropic -> OpenAI -> Gemini (based on API key availability).
    pub async fn describe_image(
        &self,
        attachment: &MediaAttachment,
    ) -> Result<MediaUnderstanding, String> {
        attachment.validate()?;
        if attachment.media_type != MediaType::Image {
            return Err("Expected image attachment".into());
        }

        // Determine which provider to use
        let provider = configured_provider(self.config.image_provider.as_deref())
            .or(detect_vision_provider())
            .ok_or("No vision-capable LLM provider configured. Set ANTHROPIC_API_KEY, OPENAI_API_KEY, or GEMINI_API_KEY")?;

        // For now, return a structured result indicating the provider.
        // Actual API call would go here using reqwest.
        Ok(MediaUnderstanding {
            media_type: MediaType::Image,
            description: format!(
                "[Image description would be generated by {} provider]",
                provider
            ),
            provider: provider.to_string(),
            model: default_vision_model(provider).to_string(),
        })
    }

    /// Transcribe audio using speech-to-text.
    /// Auto-cascade: Groq (whisper-large-v3-turbo) -> OpenAI (whisper-1) -> local.
    pub async fn transcribe_audio(
        &self,
        attachment: &MediaAttachment,
    ) -> Result<MediaUnderstanding, String> {
        attachment.validate()?;
        if attachment.media_type != MediaType::Audio {
            return Err("Expected audio attachment".into());
        }
        if !self.config.audio_transcription {
            return Err("Audio transcription is disabled in configuration".into());
        }

        let provider = self.config.audio_provider.as_deref();
        let provider = configured_provider(provider)
            .or(detect_audio_provider())
            .ok_or(
                "No audio transcription provider configured. Set GROQ_API_KEY, OPENAI_API_KEY, or media.audio_provider='local'",
            )?;

        let _permit = self.semaphore.acquire().await.map_err(|e| e.to_string())?;

        // Derive a proper filename with extension from mime_type
        // (Whisper APIs require an extension to detect format)
        let ext = match attachment.mime_type.as_str() {
            "audio/wav" => "wav",
            "audio/mpeg" | "audio/mp3" => "mp3",
            "audio/ogg" => "ogg",
            "audio/webm" => "webm",
            "audio/mp4" | "audio/m4a" => "m4a",
            "audio/flac" => "flac",
            _ => "wav",
        };

        // Read audio bytes from source
        let audio_bytes = match &attachment.source {
            MediaSource::FilePath { path } => tokio::fs::read(path)
                .await
                .map_err(|e| format!("Failed to read audio file '{}': {}", path, e))?,
            MediaSource::Base64 { data, .. } => {
                use base64::Engine;
                base64::engine::general_purpose::STANDARD
                    .decode(data)
                    .map_err(|e| format!("Failed to decode base64 audio: {}", e))?
            }
            MediaSource::Url { url } => {
                return Err(format!(
                    "URL-based audio source not supported for transcription: {}",
                    url
                ));
            }
        };
        let filename = format!("audio.{}", ext);
        let (transcription, model) = match provider {
            "local" => {
                self.transcribe_audio_local(&audio_bytes, &filename, &attachment.mime_type)
                    .await?
            }
            "groq" | "openai" => {
                self.transcribe_audio_cloud(
                    provider,
                    &audio_bytes,
                    &filename,
                    &attachment.mime_type,
                )
                .await?
            }
            other => return Err(format!("Unsupported audio provider: {}", other)),
        };

        let transcription = transcription.trim().to_string();
        if transcription.is_empty() {
            return Err("Transcription returned empty text".into());
        }

        info!(
            provider,
            model = %model,
            chars = transcription.len(),
            "Audio transcription complete"
        );

        Ok(MediaUnderstanding {
            media_type: MediaType::Audio,
            description: transcription,
            provider: provider.to_string(),
            model,
        })
    }

    /// Describe video using Gemini.
    pub async fn describe_video(
        &self,
        attachment: &MediaAttachment,
    ) -> Result<MediaUnderstanding, String> {
        attachment.validate()?;
        if attachment.media_type != MediaType::Video {
            return Err("Expected video attachment".into());
        }

        if !self.config.video_description {
            return Err("Video description is disabled in configuration".into());
        }

        if std::env::var("GEMINI_API_KEY").is_err() && std::env::var("GOOGLE_API_KEY").is_err() {
            return Err("Video description requires GEMINI_API_KEY or GOOGLE_API_KEY".into());
        }

        Ok(MediaUnderstanding {
            media_type: MediaType::Video,
            description: "[Video description would be generated by Gemini]".to_string(),
            provider: "gemini".to_string(),
            model: "gemini-2.5-flash".to_string(),
        })
    }

    /// Process multiple attachments concurrently (bounded by max_concurrency).
    pub async fn process_attachments(
        &self,
        attachments: Vec<MediaAttachment>,
    ) -> Vec<Result<MediaUnderstanding, String>> {
        let mut handles = Vec::new();

        for attachment in attachments {
            let sem = self.semaphore.clone();
            let config = self.config.clone();
            let handle = tokio::spawn(async move {
                let _permit = sem.acquire().await.map_err(|e| e.to_string())?;
                let engine = MediaEngine {
                    config,
                    semaphore: Arc::new(Semaphore::new(1)), // inner engine, no extra semaphore
                };
                match attachment.media_type {
                    MediaType::Image => engine.describe_image(&attachment).await,
                    MediaType::Audio => engine.transcribe_audio(&attachment).await,
                    MediaType::Video => engine.describe_video(&attachment).await,
                }
            });
            handles.push(handle);
        }

        let mut results = Vec::new();
        for handle in handles {
            match handle.await {
                Ok(result) => results.push(result),
                Err(e) => results.push(Err(format!("Task failed: {e}"))),
            }
        }
        results
    }

    async fn transcribe_audio_cloud(
        &self,
        provider: &str,
        audio_bytes: &[u8],
        filename: &str,
        mime_type: &str,
    ) -> Result<(String, String), String> {
        let model = default_audio_model(provider).to_string();

        let (api_url, api_key) = match provider {
            "groq" => (
                "https://api.groq.com/openai/v1/audio/transcriptions",
                std::env::var("GROQ_API_KEY").map_err(|_| "GROQ_API_KEY not set")?,
            ),
            "openai" => (
                "https://api.openai.com/v1/audio/transcriptions",
                std::env::var("OPENAI_API_KEY").map_err(|_| "OPENAI_API_KEY not set")?,
            ),
            other => return Err(format!("Unsupported cloud audio provider: {other}")),
        };

        info!(
            provider,
            model = %model,
            filename = %filename,
            size = audio_bytes.len(),
            "Sending audio for transcription"
        );

        let file_part = reqwest::multipart::Part::bytes(audio_bytes.to_vec())
            .file_name(filename.to_string())
            .mime_str(mime_type)
            .map_err(|e| format!("Failed to set MIME type: {e}"))?;

        let form = reqwest::multipart::Form::new()
            .part("file", file_part)
            .text("model", model.clone())
            .text("response_format", "text");

        let client = reqwest::Client::new();
        let resp = client
            .post(api_url)
            .bearer_auth(&api_key)
            .multipart(form)
            .timeout(Duration::from_secs(60))
            .send()
            .await
            .map_err(|e| format!("Transcription request failed: {e}"))?;

        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            return Err(format!("Transcription API error ({status}): {body}"));
        }

        let transcription = resp
            .text()
            .await
            .map_err(|e| format!("Failed to read transcription response: {e}"))?;
        Ok((transcription, model))
    }

    async fn transcribe_audio_local(
        &self,
        audio_bytes: &[u8],
        filename: &str,
        mime_type: &str,
    ) -> Result<(String, String), String> {
        let endpoint = configured_provider(self.config.audio_local_endpoint.as_deref())
            .map(ToString::to_string)
            .or_else(|| non_empty_env("OPENFANG_STT_LOCAL_ENDPOINT"));
        let model = configured_provider(Some(self.config.audio_local_model.as_str()))
            .map(ToString::to_string)
            .or_else(|| non_empty_env("OPENFANG_STT_LOCAL_MODEL"))
            .unwrap_or_else(|| "base".to_string());
        let language = configured_provider(self.config.audio_local_language.as_deref())
            .map(ToString::to_string)
            .or_else(|| non_empty_env("OPENFANG_STT_LOCAL_LANG"));
        let timeout_secs = parse_env_u64("OPENFANG_STT_LOCAL_TIMEOUT_SECS")
            .unwrap_or(self.config.audio_local_timeout_secs)
            .clamp(5, 600);

        if let Some(endpoint_url) = endpoint {
            let text = self
                .transcribe_audio_local_http(
                    &endpoint_url,
                    &model,
                    language.as_deref(),
                    timeout_secs,
                    audio_bytes,
                    filename,
                    mime_type,
                )
                .await?;
            return Ok((text, model));
        }

        let bin = configured_provider(Some(self.config.audio_local_bin.as_str()))
            .map(ToString::to_string)
            .or_else(|| non_empty_env("OPENFANG_STT_LOCAL_BIN"))
            .unwrap_or_else(|| "whisper".to_string());
        let text = self
            .transcribe_audio_local_cli(
                &bin,
                &model,
                language.as_deref(),
                timeout_secs,
                audio_bytes,
                filename,
            )
            .await?;
        Ok((text, model))
    }

    #[allow(clippy::too_many_arguments)]
    async fn transcribe_audio_local_http(
        &self,
        endpoint: &str,
        model: &str,
        language: Option<&str>,
        timeout_secs: u64,
        audio_bytes: &[u8],
        filename: &str,
        mime_type: &str,
    ) -> Result<String, String> {
        let endpoint_lower = endpoint.to_ascii_lowercase();
        let is_openai_style = endpoint_lower.contains("/v1/audio/transcriptions");
        let field_name = if is_openai_style { "file" } else { "audio" };

        let file_part = reqwest::multipart::Part::bytes(audio_bytes.to_vec())
            .file_name(filename.to_string())
            .mime_str(mime_type)
            .map_err(|e| format!("Failed to set MIME type: {e}"))?;

        let mut form = reqwest::multipart::Form::new()
            .part(field_name, file_part)
            .text("model", model.to_string());

        if is_openai_style {
            form = form.text("response_format", "text");
            if let Some(lang) = language {
                form = form.text("language", lang.to_string());
            }
        } else if let Some(lang) = language {
            form = form.text("preferred_lang", lang.to_string());
        }

        let client = reqwest::Client::new();
        let resp = client
            .post(endpoint)
            .multipart(form)
            .timeout(Duration::from_secs(timeout_secs))
            .send()
            .await
            .map_err(|e| format!("Local STT request failed: {e}"))?;

        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            return Err(format!("Local STT API error ({status}): {body}"));
        }

        let content_type = resp
            .headers()
            .get(reqwest::header::CONTENT_TYPE)
            .and_then(|v| v.to_str().ok())
            .unwrap_or("")
            .to_ascii_lowercase();
        let body = resp
            .bytes()
            .await
            .map_err(|e| format!("Failed to read local STT response: {e}"))?;

        extract_transcription_text(&body, &content_type)
            .ok_or_else(|| "Local STT response did not include transcription text".to_string())
    }

    async fn transcribe_audio_local_cli(
        &self,
        bin: &str,
        model: &str,
        language: Option<&str>,
        timeout_secs: u64,
        audio_bytes: &[u8],
        filename: &str,
    ) -> Result<String, String> {
        let temp_dir = std::env::temp_dir().join(format!("openfang-stt-{}", uuid::Uuid::new_v4()));
        tokio::fs::create_dir_all(&temp_dir)
            .await
            .map_err(|e| format!("Failed to create temp directory for local STT: {e}"))?;

        let result = async {
            let input_path = temp_dir.join(filename);
            tokio::fs::write(&input_path, audio_bytes)
                .await
                .map_err(|e| format!("Failed to write temp audio file for local STT: {e}"))?;

            let mut cmd = Command::new(bin);
            cmd.arg(&input_path)
                .arg("--model")
                .arg(model)
                .arg("--output_format")
                .arg("txt")
                .arg("--output_dir")
                .arg(&temp_dir)
                .arg("--fp16")
                .arg("False");
            if let Some(lang) = language {
                cmd.arg("--language").arg(lang);
            }

            let output = tokio::time::timeout(Duration::from_secs(timeout_secs), cmd.output())
                .await
                .map_err(|_| {
                    format!(
                        "Local STT CLI timed out after {timeout_secs}s (binary: '{bin}')"
                    )
                })?
                .map_err(|e| {
                    format!("Failed to start local STT binary '{bin}'. Install OpenAI whisper CLI or set media.audio_local_endpoint. Error: {e}")
                })?;

            if !output.status.success() {
                let stderr = String::from_utf8_lossy(&output.stderr);
                return Err(format!(
                    "Local STT CLI failed (code {:?}): {}",
                    output.status.code(),
                    stderr.trim()
                ));
            }

            let stem = Path::new(filename)
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("audio");
            let txt_path = temp_dir.join(format!("{stem}.txt"));
            let text = tokio::fs::read_to_string(&txt_path).await.map_err(|e| {
                format!(
                    "Local STT CLI finished but no transcript file found at {}: {e}",
                    txt_path.display()
                )
            })?;
            Ok(text)
        }
        .await;

        let _ = tokio::fs::remove_dir_all(&temp_dir).await;
        result
    }
}

/// Detect which vision provider is available based on environment variables.
fn detect_vision_provider() -> Option<&'static str> {
    if std::env::var("ANTHROPIC_API_KEY").is_ok() {
        return Some("anthropic");
    }
    if std::env::var("OPENAI_API_KEY").is_ok() {
        return Some("openai");
    }
    if std::env::var("GEMINI_API_KEY").is_ok() || std::env::var("GOOGLE_API_KEY").is_ok() {
        return Some("gemini");
    }
    None
}

fn configured_provider(value: Option<&str>) -> Option<&str> {
    value
        .map(str::trim)
        .filter(|v| !v.is_empty() && !v.eq_ignore_ascii_case("auto"))
}

fn non_empty_env(key: &str) -> Option<String> {
    std::env::var(key)
        .ok()
        .map(|v| v.trim().to_string())
        .filter(|v| !v.is_empty())
}

fn parse_env_u64(key: &str) -> Option<u64> {
    non_empty_env(key).and_then(|v| v.parse::<u64>().ok())
}

fn extract_transcription_text(body: &[u8], content_type: &str) -> Option<String> {
    let looks_json = content_type.contains("application/json");
    if looks_json {
        if let Ok(json) = serde_json::from_slice::<serde_json::Value>(body) {
            if let Some(text) = extract_transcription_text_from_json(&json) {
                return Some(text);
            }
        }
    }

    if let Ok(text) = std::str::from_utf8(body) {
        let trimmed = text.trim();
        if trimmed.is_empty() {
            return None;
        }
        if !looks_json {
            return Some(trimmed.to_string());
        }
        if let Ok(json) = serde_json::from_str::<serde_json::Value>(trimmed) {
            if let Some(parsed) = extract_transcription_text_from_json(&json) {
                return Some(parsed);
            }
        }
        return Some(trimmed.to_string());
    }
    None
}

fn extract_transcription_text_from_json(json: &serde_json::Value) -> Option<String> {
    const POINTERS: [&str; 6] = [
        "/text",
        "/transcription",
        "/result",
        "/message",
        "/data/text",
        "/data/transcription",
    ];
    for pointer in POINTERS {
        if let Some(text) = json
            .pointer(pointer)
            .and_then(|v| v.as_str())
            .map(str::trim)
            .filter(|v| !v.is_empty())
        {
            return Some(text.to_string());
        }
    }
    None
}

/// Detect which audio transcription provider is available.
fn detect_audio_provider() -> Option<&'static str> {
    if std::env::var("GROQ_API_KEY").is_ok() {
        return Some("groq");
    }
    if std::env::var("OPENAI_API_KEY").is_ok() {
        return Some("openai");
    }
    if non_empty_env("OPENFANG_STT_LOCAL_ENDPOINT").is_some()
        || non_empty_env("OPENFANG_STT_LOCAL_BIN").is_some()
    {
        return Some("local");
    }
    None
}

/// Get the default vision model for a provider.
fn default_vision_model(provider: &str) -> &str {
    match provider {
        "anthropic" => "claude-sonnet-4-20250514",
        "openai" => "gpt-4o",
        "gemini" => "gemini-2.5-flash",
        _ => "unknown",
    }
}

/// Get the default audio model for a provider.
fn default_audio_model(provider: &str) -> &str {
    match provider {
        "groq" => "whisper-large-v3-turbo",
        "openai" => "whisper-1",
        "local" => "base",
        _ => "unknown",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use openfang_types::media::{MediaSource, MAX_IMAGE_BYTES};

    #[test]
    fn test_engine_creation() {
        let config = MediaConfig::default();
        let engine = MediaEngine::new(config);
        assert_eq!(engine.config.max_concurrency, 2);
    }

    #[test]
    fn test_engine_max_concurrency_clamped() {
        let config = MediaConfig {
            max_concurrency: 100,
            ..Default::default()
        };
        let engine = MediaEngine::new(config);
        // Semaphore was clamped to 8
        assert!(engine.semaphore.available_permits() <= 8);
    }

    #[tokio::test]
    async fn test_describe_image_wrong_type() {
        let engine = MediaEngine::new(MediaConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Audio,
            mime_type: "audio/mpeg".into(),
            source: MediaSource::FilePath {
                path: "test.mp3".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.describe_image(&attachment).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Expected image"));
    }

    #[tokio::test]
    async fn test_describe_image_invalid_mime() {
        let engine = MediaEngine::new(MediaConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Image,
            mime_type: "application/pdf".into(),
            source: MediaSource::FilePath {
                path: "test.pdf".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.describe_image(&attachment).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_describe_image_too_large() {
        let engine = MediaEngine::new(MediaConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Image,
            mime_type: "image/png".into(),
            source: MediaSource::FilePath {
                path: "big.png".into(),
            },
            size_bytes: MAX_IMAGE_BYTES + 1,
        };
        let result = engine.describe_image(&attachment).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_transcribe_audio_wrong_type() {
        let engine = MediaEngine::new(MediaConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Image,
            mime_type: "image/png".into(),
            source: MediaSource::FilePath {
                path: "test.png".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_video_disabled() {
        let config = MediaConfig {
            video_description: false,
            ..Default::default()
        };
        let engine = MediaEngine::new(config);
        let attachment = MediaAttachment {
            media_type: MediaType::Video,
            mime_type: "video/mp4".into(),
            source: MediaSource::FilePath {
                path: "test.mp4".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.describe_video(&attachment).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("disabled"));
    }

    #[test]
    fn test_detect_vision_provider_none() {
        // In test env, likely no API keys set — should return None.
        // (This test is environment-dependent, but safe.)
        let _ = detect_vision_provider(); // Just verify it doesn't panic
    }

    #[test]
    fn test_default_vision_models() {
        assert_eq!(
            default_vision_model("anthropic"),
            "claude-sonnet-4-20250514"
        );
        assert_eq!(default_vision_model("openai"), "gpt-4o");
        assert_eq!(default_vision_model("gemini"), "gemini-2.5-flash");
        assert_eq!(default_vision_model("unknown"), "unknown");
    }

    #[test]
    fn test_default_audio_models() {
        assert_eq!(default_audio_model("groq"), "whisper-large-v3-turbo");
        assert_eq!(default_audio_model("openai"), "whisper-1");
        assert_eq!(default_audio_model("local"), "base");
    }

    #[tokio::test]
    async fn test_transcribe_audio_rejects_image_type() {
        let engine = MediaEngine::new(MediaConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Image,
            mime_type: "image/png".into(),
            source: MediaSource::FilePath {
                path: "test.png".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Expected audio"));
    }

    #[tokio::test]
    async fn test_transcribe_audio_no_provider() {
        // With no API keys set, should fail with provider error
        let engine = MediaEngine::new(MediaConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Audio,
            mime_type: "audio/webm".into(),
            source: MediaSource::FilePath {
                path: "test.webm".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        // Either fails with "No audio transcription provider" or file read error
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_transcribe_audio_url_source_rejected() {
        // URL source should be rejected
        let config = MediaConfig {
            audio_provider: Some("groq".to_string()),
            ..Default::default()
        };
        let engine = MediaEngine::new(config);
        let attachment = MediaAttachment {
            media_type: MediaType::Audio,
            mime_type: "audio/mpeg".into(),
            source: MediaSource::Url {
                url: "https://example.com/audio.mp3".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .contains("URL-based audio source not supported"));
    }

    #[tokio::test]
    async fn test_transcribe_audio_file_not_found() {
        let config = MediaConfig {
            audio_provider: Some("groq".to_string()),
            ..Default::default()
        };
        let engine = MediaEngine::new(config);
        let attachment = MediaAttachment {
            media_type: MediaType::Audio,
            mime_type: "audio/webm".into(),
            source: MediaSource::FilePath {
                path: "/nonexistent/path/audio.webm".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Failed to read audio file"));
    }

    #[tokio::test]
    async fn test_transcribe_audio_local_missing_binary() {
        let config = MediaConfig {
            audio_provider: Some("local".to_string()),
            audio_local_endpoint: None,
            audio_local_bin: "/definitely/missing/whisper".to_string(),
            ..Default::default()
        };
        let engine = MediaEngine::new(config);
        let attachment = MediaAttachment {
            media_type: MediaType::Audio,
            mime_type: "audio/webm".into(),
            source: MediaSource::Base64 {
                data: "dGVzdA==".into(),
                mime_type: "audio/webm".into(),
            },
            size_bytes: 4,
        };
        let result = engine.transcribe_audio(&attachment).await;
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .contains("Failed to start local STT binary"));
    }

    #[test]
    fn test_extract_transcription_text_from_json() {
        let body = br#"{"text":"hallo welt"}"#;
        let text = extract_transcription_text(body, "application/json");
        assert_eq!(text.as_deref(), Some("hallo welt"));
    }
}
